name: fix-code-style-mongodb

on:
  push:

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt update
          sudo apt-get install php-mongodb
          composer install --no-interaction
      - name: Run Pint
        run: ./vendor/bin/pint
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: fix code style'
